# Generated by Django 3.1.6 on 2021-02-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_file_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch_Scrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.NullBooleanField(default=False)),
            ],
        ),
    ]
