# Generated by Django 3.1.6 on 2021-02-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_switch_scrap'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='column',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
