# Generated by Django 3.1.6 on 2021-03-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_file_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fileName',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
